### ISSUE TITLE
运行make_conll2012_data.sh

### ISSUE THREAD

**Issue by 2177361170** [royyoung388/chinese-self-attention-srl#1]
我在运行上述命令时为什么输出的文件都是空的
![2023-04-06 21-37-33 的屏幕截图](https://user-images.githubusercontent.com/83916854/230395013-176ccfd2-4670-400c-ad04-0226e89a1b01.png)

**Comment by royyoung388** [comment]
你的数据集路径设置都正确吗？脚本中有三个变量需要修改的。
能发一下你的脚本代码吗

**Comment by 2177361170** [comment]
这个问题我解决了，是因为我在处理conll文件时的问题。
![2023-04-07 13-03-11 的屏幕截图](https://user-images.githubusercontent.com/83916854/230544451-2001f6ca-3061-4722-bf07-9431a6e3c303.png)
但是也有部分是0的情况
现在有个新问题，就是我运行./run/sh时会出现"没有data/glove/enbedding.txt"的问题。请问这个文件是在哪一次命令中生成的？

**Comment by 2177361170** [comment]
最新的问题
![2023-04-07 22-37-29 的屏幕截图](https://user-images.githubusercontent.com/83916854/230627106-8c25ba7b-da8d-49d4-9fe3-f0de5e2554a1.png)


这个bin/srl-eval.pl 文件是从哪里来的

**Comment by royyoung388** [comment]
具体想不起来了，推测是训练过程保存的模型，可以看看代码，能不能设置为空

**Comment by 2177361170** [comment]
万分感谢 @royyoung388
